### ISSUE TITLE
Error compiling equals-hashcode-test plugin

### ISSUE THREAD

**Issue by arturoherrero** [osoco/grails-equals-hashcode#3]
Seems to be an error related with the downloaded order between spock and equals-hashcode-test plugins.

```
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] /root/.grails/1.3.9/projects/trunk/plugins/equals-hashcode-test-0.3/src/groovy/es/osoco/grails/plugins/EqualsHashCodeSpec.groovy: 4: unable to resolve class grails.plugin.spock.UnitSpec
  [groovyc]  @ line 4, column 1.
  [groovyc]    import grails.plugin.spock.UnitSpec
  [groovyc]    ^
  [groovyc]
  [groovyc] /root/.grails/1.3.9/projects/trunk/plugins/equals-hashcode-test-0.3/src/groovy/es/osoco/grails/plugins/EqualsHashCodeSpec.groovy: 3: unable to resolve class spock.lang.Unroll
  [groovyc]  @ line 3, column 1.
  [groovyc]    import spock.lang.Unroll
  [groovyc]    ^
  [groovyc]
  [groovyc] /root/.grails/1.3.9/projects/trunk/plugins/equals-hashcode-test-0.3/src/groovy/es/osoco/grails/plugins/EqualsHashCodeSpec.groovy: 6: unable to resolve class grails.plugin.spock.UnitSpec
  [groovyc]  @ line 6, column 1.
  [groovyc]    class EqualsHashCodeSpec extends UnitSpec {
  [groovyc]    ^
  [groovyc]
  [groovyc] /root/.grails/1.3.9/projects/trunk/plugins/equals-hashcode-test-0.3/src/groovy/es/osoco/grails/plugins/EqualsHashCodeSpec.groovy: 84: unable to resolve class spock.lang.Unroll ,  unable to find class for annotation
  [groovyc]  @ line 84, column 5.
  [groovyc]        @Unroll("equals and hashCode use #property")
  [groovyc]        ^
  [groovyc]
  [groovyc] /root/.grails/1.3.9/projects/trunk/plugins/equals-hashcode-test-0.3/src/groovy/es/osoco/grails/plugins/EqualsHashCodeSpec.groovy: 99: unable to resolve class spock.lang.Unroll ,  unable to find class for annotation
  [groovyc]  @ line 99, column 5.
  [groovyc]        @Unroll("equals and hashCode ignore #property")
  [groovyc]        ^
  [groovyc]
  [groovyc] 5 errors
Error executing script Compile: : Compilation Failed
: Compilation Failed
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:391)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:590)
    at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: : Compilation Failed
    at org.codehaus.groovy.ant.Groovyc.compile(Groovyc.java:920)
    at org.codehaus.groovy.ant.Groovyc.execute(Groovyc.java:607)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at _GrailsCompile_groovy$_run_closure4_closure10.doCall(_GrailsCompile_groovy:117)
    at _GrailsCompile_groovy$_run_closure4_closure10.doCall(_GrailsCompile_groovy)
    at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:280)
    at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
    at _GrailsCompile_groovy$_run_closure4.doCall(_GrailsCompile_groovy:104)
    at _GrailsCompile_groovy$_run_closure3.doCall(_GrailsCompile_groovy:69)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    ... 10 more
```

**Comment by mgryszko** [comment]
Clone the repo and try the HEAD version. Now the plugin should be loaded after Spock.
